// One proxy <-> GROWI pairing (design.md's `relation` table).
//
// Nothing here is encrypted. What this repository is responsible for instead is
// keeping the several GROWI instances one workspace may be paired with apart
// (Requirement 8.1): every lookup that is not by `relationId` is addressed by
// `(installationId, growiUri)`, which is the table's unique key -- `growiUri`
// alone is not unique, because two workspaces may each pair the same GROWI.
//
// `id` is generated by the database as a UUID rather than a sequence: it
// travels outward as the `keyid` parameter of the signature header, so a
// sequential value would leak how many relations exist and let one be guessed
// from another (design.md's Data Models note on this column).

import { Prisma } from '../../generated/prisma/client.js';
import type { Relation } from '../../types/index.js';
import type { DbClient } from '../prisma-client.js';

/**
 * The `(installation_id, growi_uri)` unique constraint, reported as something
 * a caller outside `db/` can act on.
 *
 * It has to be translated here rather than at the call site: Prisma reports a
 * constraint violation as `PrismaClientKnownRequestError` with code `P2002`,
 * and that type lives under `src/generated/**`, which only `db/` may import
 * (`architecture.spec.ts` guard 3). Without this, `PairingService` could only
 * recognise the race by string-matching an opaque error.
 */
export class RelationAlreadyExistsError extends Error {
  constructor(
    readonly installationId: string,
    readonly growiUri: string,
  ) {
    super(`${growiUri} is already paired with installation ${installationId}.`);
    this.name = 'RelationAlreadyExistsError';
  }
}

const isUniqueViolation = (error: unknown): boolean =>
  error instanceof Prisma.PrismaClientKnownRequestError &&
  error.code === 'P2002';

/** The columns a caller supplies; `id` and `createdAt` come from the database. */
export interface NewRelation {
  readonly installationId: string;
  readonly growiUri: string;
  readonly growiLabel: string;
  readonly searchWeight: number;
  readonly settingsVersion: number;
}

export interface RelationRepository {
  /**
   * Throws {@link RelationAlreadyExistsError} when the same GROWI is already
   * paired with this installation -- `(installation_id, growi_uri)` is unique,
   * which is what makes a second pairing attempt answer `already-paired`
   * (Requirement 8.5) instead of silently creating a duplicate. A caller that
   * looked first still needs this: the constraint is what settles two
   * submissions that both looked and both found nothing.
   */
  create(relation: NewRelation): Promise<Relation>;
  findById(relationId: string): Promise<Relation | null>;
  findByGrowiUri(
    installationId: string,
    growiUri: string,
  ): Promise<Relation | null>;
  listByInstallation(installationId: string): Promise<ReadonlyArray<Relation>>;
  /**
   * Deletes the relation row alone. Its children are `Restrict`, so this fails
   * while any remain; the ordered removal design.md specifies for unpairing is
   * composed by `PairingService.unpair()`, which owns that whole unit of work.
   */
  remove(relationId: string): Promise<void>;
}

interface RelationRow {
  readonly id: string;
  readonly installationId: string;
  readonly growiUri: string;
  readonly growiLabel: string;
  readonly searchWeight: number;
  readonly settingsVersion: number;
  readonly createdAt: Date;
}

const toRelation = (row: RelationRow): Relation => ({
  relationId: row.id,
  installationId: row.installationId,
  growiUri: row.growiUri,
  growiLabel: row.growiLabel,
  searchWeight: row.searchWeight,
  settingsVersion: row.settingsVersion,
  createdAt: row.createdAt,
});

export const createRelationRepository = (db: DbClient): RelationRepository => ({
  create: async (relation) => {
    try {
      return toRelation(await db.relation.create({ data: { ...relation } }));
    } catch (error) {
      if (isUniqueViolation(error)) {
        throw new RelationAlreadyExistsError(
          relation.installationId,
          relation.growiUri,
        );
      }
      throw error;
    }
  },

  findById: async (relationId) => {
    const row = await db.relation.findUnique({ where: { id: relationId } });
    return row == null ? null : toRelation(row);
  },

  findByGrowiUri: async (installationId, growiUri) => {
    const row = await db.relation.findUnique({
      where: { installationId_growiUri: { installationId, growiUri } },
    });
    return row == null ? null : toRelation(row);
  },

  listByInstallation: async (installationId) => {
    const rows = await db.relation.findMany({ where: { installationId } });
    return rows.map(toRelation);
  },

  remove: async (relationId) => {
    await db.relation.delete({ where: { id: relationId } });
  },
});
