export interface IEditorMethods {
  forceToFocus: () => void,
  setValue: (newValue: string) => void,
  setGfmMode: (bool: boolean) => void,
  setCaretLine: (line: number) => void,
  setScrollTopByLine: (line: number) => void,
  getStrFromBol(): void,
  getStrToEol: () => void,
  getStrFromBolToSelectedUpperPos: () => void,
  replaceBolToCurrentPos: (text: string) => void,
  replaceLine: (text: string) => void,
  insertText: (text: string) => void,
  insertLinebreak: () => void,
  dispatchSave: () => void,
  dispatchPasteFiles: (event: Event) => void,
  getNavbarItems: () => JSX.Element[],
}
