queue_rules:
  - name: default
    allow_inplace_checks: false
    queue_conditions:
      - check-success ~= ci-app-lint
      - check-success ~= ci-app-test
      - check-success ~= ci-app-launch-dev
      - -check-failure ~= ci-app-
      - -check-failure ~= ci-slackbot-
      - -check-failure ~= test-prod-node22 /
    merge_conditions:
      - check-success ~= ci-app-lint
      - check-success ~= ci-app-test
      - check-success ~= ci-app-launch-dev
      - check-success ~= test-prod-node22 / build-prod
      - check-success ~= test-prod-node22 / launch-prod
      - check-success ~= test-prod-node22 / run-playwright
      - -check-failure ~= ci-app-
      - -check-failure ~= ci-slackbot-
      - -check-failure ~= test-prod-node22 /

pull_request_rules:
  - name: Automatic queue to merge
    conditions:
      - '#approved-reviews-by >= 1'
      - '#changes-requested-reviews-by = 0'
      - '#review-requested = 0'
    actions:
      queue:

  - name: Automatic merge for Preparing next version
    conditions:
      - author = github-actions[bot]
      - label = type/prepare-next-version
    actions:
      merge:
        method: merge
