pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
      - '#approved-reviews-by >= 1'
      - check-success = "lint (20.x)"
      - check-success = "test (20.x)"
      - check-success = "launch-dev (20.x)"
      - check-success = "test-prod-node18 / launch-prod"
      - check-success = "test-prod-node20 / launch-prod"
    actions:
      merge:
        method: merge

  - name: Automatic merge for Preparing next version
    conditions:
      - author = github-actions[bot]
      - label = "type/prepare-next-version"
    actions:
      merge:
        method: merge
