import type { GrowiThemeMetadata } from '@growi/core';
import { GrowiThemeSchemeType } from '@growi/core';

const { BOTH, LIGHT, DARK } = GrowiThemeSchemeType;

export const PresetThemes = {
  DEFAULT: 'default',
  ANTARCTIC: 'antarctic',
  BLACKBOARD: 'blackboard',
  CHRISTMAS: 'christmas',
  FIRE_RED: 'fire-red',
  FUTURE: 'future',
  HALLOWEEN: 'halloween',
  HUFFLEPUFF: 'hufflepuff',
  ISLAND: 'island',
  JADE_GREEN: 'jade-green',
  KIBELA: 'kibela',
  MONO_BLUE: 'mono-blue',
  NATURE: 'nature',
  SPRING: 'spring',
  WOOD: 'wood',
  CLASSIC: 'classic',
} as const;
export type PresetThemes = (typeof PresetThemes)[keyof typeof PresetThemes];

/* eslint-disable no-multi-spaces, */

export const DefaultThemeMetadata: GrowiThemeMetadata = {
  name: PresetThemes.DEFAULT,
  manifestKey: `src/styles/${PresetThemes.DEFAULT}.scss`,
  schemeType: BOTH,
  lightBg: '#FFFFFF',
  darkBg: '#1C1A1A',
  lightSidebar: '#F8F7F7',
  darkSidebar: '#434240',
  lightIcon: '#8A8887',
  darkIcon: '#D1D0CC',
  createBtn: '#007EB0',
  isPresetTheme: true,
};

export const PresetThemesMetadatas: GrowiThemeMetadata[] = [
  // support both of light and dark
  DefaultThemeMetadata,
  {
    name: PresetThemes.MONO_BLUE,
    schemeType: BOTH,
    lightBg: '#FFFFFF',
    darkBg: '#16202C',
    lightSidebar: '#EDFAFD',
    darkSidebar: '#0A2E53',
    lightIcon: '#36819C',
    darkIcon: '#69B0C7',
    createBtn: '#439CB9',
  },
  {
    name: PresetThemes.HUFFLEPUFF,
    schemeType: BOTH,
    lightBg: '#FFFEFD',
    darkBg: '#26231E',
    lightSidebar: '#FEEBA5',
    darkSidebar: '#5C4209',
    lightIcon: '#B88512',
    darkIcon: '#EBB845',
    createBtn: '#403C39',
  },
  {
    name: PresetThemes.FIRE_RED,
    schemeType: BOTH,
    lightBg: '#FFFFFF',
    darkBg: '#120700',
    lightSidebar: '#FADDD6',
    darkSidebar: '#5A4F4A',
    lightIcon: '#94351E',
    darkIcon: '#EE775B',
    createBtn: '#EA5532',
  },
  {
    name: PresetThemes.JADE_GREEN,
    schemeType: BOTH,
    lightBg: '#FFFFFF',
    darkBg: '#120700',
    lightSidebar: '#F1F3F2',
    darkSidebar: '#4B4E4C',
    lightIcon: '#3A8F6F',
    darkIcon: '#5FC2A2',
    createBtn: '#49B38A',
  },
  {
    name: PresetThemes.CLASSIC,
    schemeType: BOTH,
    lightBg: '#FFFFFF',
    darkBg: '#151A1F',
    lightSidebar: '#F0F4FA',
    darkSidebar: '#29343F',
    lightIcon: '#53687E',
    darkIcon: '#869BB1',
    createBtn: '#3491CB',
  },
  {
    name: PresetThemes.CHRISTMAS,
    schemeType: BOTH,
    lightBg: '#FFFFFF',
    darkBg: '#001B30',
    lightSidebar: '#EEE8C4',
    darkSidebar: '#0C3811',
    lightIcon: '#801218',
    darkIcon: '#f0752b',
    createBtn: '#AA1820',
  },
  // light only
  {
    name: PresetThemes.NATURE,
    schemeType: LIGHT,
    lightBg: '#FFFFFF',
    darkBg: '#FAF9F8',
    lightSidebar: '#EBF9CC',
    darkSidebar: '#D8F399',
    lightIcon: '#3F8421',
    darkIcon: '#1F4210',
    createBtn: '#4FA529',
  },
  {
    name: PresetThemes.WOOD,
    schemeType: LIGHT,
    lightBg: '#FFFFF5',
    darkBg: '#FDFAF0',
    lightSidebar: '#EAE3D4',
    darkSidebar: '#DCCBA6',
    lightIcon: '#86651A',
    darkIcon: '#43320D',
    createBtn: '#A77E21',
  },
  {
    name: PresetThemes.ISLAND,
    schemeType: LIGHT,
    lightBg: '#FFFFFF',
    darkBg: '#E8F7FA',
    lightSidebar: '#F3EEE0',
    darkSidebar: '#E8DDC0',
    lightIcon: '#51C2D3',
    darkIcon: '#204D54',
    createBtn: '#51C2D3',
  },
  {
    name: PresetThemes.ANTARCTIC,
    schemeType: LIGHT,
    lightBg: '#FAFEFF',
    darkBg: '#E5FAFF',
    lightSidebar: '#EDF4FC',
    darkSidebar: '#DBE9F9',
    lightIcon: '#2631AF',
    darkIcon: '#131857',
    createBtn: '#303DDB',
  },
  {
    name: PresetThemes.SPRING,
    schemeType: LIGHT,
    lightBg: '#FFFFFF',
    darkBg: '#FFFDF5',
    lightSidebar: '#FEE7EB',
    darkSidebar: '#F9CED7',
    lightIcon: '#D76F7D',
    darkIcon: '#8A423F',
    createBtn: '#6ABA55',
  },
  {
    name: PresetThemes.KIBELA,
    schemeType: LIGHT,
    lightBg: '#FFFFFF',
    darkBg: '#F5F5F5',
    lightSidebar: '#FFFFFF',
    darkSidebar: '#F5F5F5',
    lightIcon: '#737373',
    darkIcon: '#525252',
    createBtn: '#3080C0',
  },
  // dark only
  {
    name: PresetThemes.FUTURE,
    schemeType: DARK,
    lightBg: '#092627',
    darkBg: '#1F4C4D',
    lightSidebar: '#2a2929',
    darkSidebar: '#27413D',
    lightIcon: '#3F999B',
    darkIcon: '#99E5E6',
    createBtn: '#03A2A8',
  },
  {
    name: PresetThemes.HALLOWEEN,
    schemeType: DARK,
    lightBg: '#240E3E',
    darkBg: '#2F1155',
    lightSidebar: '#2F1155',
    darkSidebar: '#3B136C',
    lightIcon: '#8C3C03',
    darkIcon: '#DDB69B',
    createBtn: '#AA4A04',
  },
  {
    name: PresetThemes.BLACKBOARD,
    schemeType: DARK,
    lightBg: '#223323',
    darkBg: '#213E23',
    lightSidebar: '#1B431C',
    darkSidebar: '#29652B',
    lightIcon: '#C89D3B',
    darkIcon: '#E3CE9D',
    createBtn: '#BA840A',
  },
]
  // fill in missing information
  .map((metadata) => {
    return {
      ...metadata,
      isPresetTheme: true,
      manifestKey: `src/styles/${metadata.name}.scss`,
    };
  });
/* eslint-disable no-multi-spaces */
