/**
 * VO for TransferKey which has appUrl and key as its public member
 */
export class TransferKey {

  private static _internalSeperator = '__grw_internal_tranferkey__';

  public appUrl: URL;

  public key: string;

  constructor(appUrl: URL, key: string) {
    this.appUrl = appUrl;
    this.key = key;
  }

  get getKeyString(): string {
    return TransferKey.generateKeyString(this.key, this.appUrl);
  }

  /**
   * Parse a transfer key string generated by the generateKeyString static method
   * @param {string} keyString Transfer key string
   * @returns {TransferKey}
   */
  static parse(keyString: string): TransferKey {
    const generalErrorPhrase = 'Failed to parse TransferKey from string';

    const splitted = keyString.split(TransferKey._internalSeperator);

    if (splitted.length !== 2) {
      throw Error(generalErrorPhrase);
    }
    const key = splitted[0];
    const appUrlString = splitted[1];

    let appUrl: URL | null;
    try {
      appUrl = new URL(appUrlString);
    }
    catch (e) {
      throw Error(generalErrorPhrase + (e as Error));
    }

    return new TransferKey(appUrl, key);
  }

  /**
   * Generates transfer key string (e.g. https://example.com:8080__grw_internal_tranferkey__key)
   * @param {string} key Key generated by GROWI
   * @param {URL} appUrl GROWI app site url
   * @returns {string} Transfer key string
   */
  static generateKeyString(key: string, appUrl: URL): string {
    return `${key}${TransferKey._internalSeperator}${appUrl.origin}`;
  }

}
