export const UserType = { admin: 'admin', general: 'general' } as const;

export type UserType = typeof UserType[keyof typeof UserType];

export interface IUserInfo {
  userIdHash: string // userId hash generated by using appSiteUrl as salt
  type: UserType
  userCreatedAt: Date // createdAt of user that answered the questionnaire
}
