const contributors = [
  {
    order: 1,
    sectionName: 'GROWI VILLAGE',
    additionalClass: '',
    memberGroups: [
      {
        additionalClass: 'col-md-12 my-4',
        members: [
          { position: 'Founder', name: 'yuki-takei' },
          { position: 'Soncho 1st', name: 'mizozobu' },
          { position: 'Soncho 2nd', name: 'yusuketk' },
          { position: 'Paladin', name: 'itizawa' },
          { position: 'Valkyrie', name: 'kaoritokashiki' },
          { position: 'Slime', name: 'TatsuyaIse' },
          { position: 'Knight', name: 'Yohei-Shiina' },
          { position: 'Titan', name: 'ryoh15' },
          { position: 'Haberion', name: 'hakumizuki' },
          { position: 'Undefind', name: 'miya' },
        ],
      },
      {
        additionalClass: 'col-md-6 my-4',
        members: [
          { name: 'zahmis' },
          { name: 'stevenfukase' },
          { name: 'sotarok' },
          { name: 'utsushiiro' },
          { name: 'maow89126' },
          { name: 'yuto-oweseek' },
          { name: 'ryu-sato' },
          { name: 'akira-sugiyama' },
          { name: 'makotoshiraishi' },
          { name: 'oshikishintaro' },
          { name: 'mayumorita' },
          { name: 'kuimac' },
          { name: 'takeru0001' },
          { name: 'sooouh' },
          { name: 'shinoka7' },
          { name: 'kaho819' },
          { name: 'haruhikonyan' },
          { name: 'suzuki' },
          { name: 'SeiyaTashiro' },
          { name: 'mudana-grune' },
          { name: 'LuqmanHakim-Grune' },
          { name: 'kaishuu0123' },
          { name: 'TsuyoshiSuzukief' },
          { name: 'KazuyaNagase' },
          { name: 'shield-9' },
          { name: 'Yuchan4342' },
          { name: 'asami-n' },
          { name: 'ryohi15' },
          { name: 'tats-u' },
          { name: 'yaodingyd' },
          { name: 'yukendev' },
          { name: 'kntowd' },
          { name: 'hitochan777' },
          { name: 'ttaka66' },
          { name: 'takayuki-t' },
          { name: 'Mxchaeltrxn' },
          { name: 'nt-7' },
          { name: 'nakashimaki' },
          { name: 'watagashi' },
          { name: 'Paramartha-Grune' },
          { name: 'b4b4r07' },
          { name: 'kouki-o' },
          { name: 'hiroppy' },
          { name: 'headhunter-Frank' },
          { name: 'riaf' },
          { name: 'hideo54' },
          { name: 'ayaka0417' },
          { name: 'yamagai' },
          { name: 'fivestar' },
          { name: 'wadahiro' },
          { name: 'Angola' },
          { name: 'shukmos' },
          { name: 'ryouhek' },
          { name: 'ryuichi-e' },
          { name: 'N1koge' },
          { name: 'Ertai87' },
          { name: 'Shu Katabe' },
          { name: 'Daiki51' },
          { name: 'fmy' },
          { name: 'kaz' },
          { name: 'yy0931' },
          { name: 'shamin' },
          { name: 'yudoufu' },
          { name: 'nukosuke' },
          { name: 'tohutohu' },
          { name: 'fumitti' },
          { name: 'rabitarochan' },
          { name: 'SSW-SCIENTIFIC' },
          { name: 'aximov' },
          { name: 'tkitsunai' },
          { name: 'amammad' },
          { name: 'ta2yak' },
          { name: 'tikuwa0max-dev' },
          { name: 'ytn86' },
          { name: 'nekoruri' },
          { name: 'stypr' },
          { name: 'yamatomo717' },
          { name: 'matsum0623' },
          { name: 'crow-misia' },
          { name: 'r-tateshina' },
          { name: 'ryo33' },
          { name: 'kmyk' },
          { name: 'kdmsnr' },
          { name: 'eltociear' },
          { name: 'bbladr' },
          { name: 'hato-poppo' },
          { name: 'inductor' },
          { name: 'mopisec' },
          { name: 'AbiFirmandhani-Grune' },
          { name: 'gitter-badger' },
          { name: 'yaamai' },
          { name: 'Poulpatine' },
          { name: 'yoshiro-s' },
          { name: 'Tomasom' },
          { name: 'chuganzy' },
        ],
      },
    ],
  },
  {
    order: 10,
    sectionName: 'CONTRIBUTER',
    additionalClass: '',
    memberGroups: [
      {
        additionalClass: 'col-md-4 my-4',
        members: [
          { name: 'inductor' },
          { name: 'shield-9' },
          { name: 'yaodingyd' },
          { name: 'hitochan777' },
          { name: 'ttaka66' },
          { name: 'watagashi' },
          { name: 'paichi81' },
          { name: 'nt-7' },
          { name: 'hideo54' },
          { name: 'wadahiro' },
        ],
      },
      {
        additionalClass: 'col-md-6 my-4',
        members: [
          { name: 'shaminmeerankutty' },
          { name: 'rabitarochan' },
        ],
      },
      {
        additionalClass: 'col-md-4 my-4',
        members: [
          { name: 'fumitti' },
          { name: 'fmy' },
          { name: 'yaamai' },
          { name: 'ta2yak' },
          { name: 'ryo33' },
          { name: 'r-tateshina' },
          { name: 'nekoruri' },
          { name: 'kmyk' },
          { name: 'aximov' },
          { name: 'tats-u' },
          { name: 'yamatomo717' },
          { name: 'tohutohu' },
        ],
      },
    ],
  },
  {
    order: 100,
    sectionName: 'VULNERABILITY HUNTER',
    additionalClass: '',
    memberGroups: [
      {
        additionalClass: 'col-md-6 my-4',
        members: [
          { name: 'Yoshinori Hayashi' },
          { name: 'Kanta Nishitani' },
          { position: 'The University of Tokyo', name: 'Takashi Yoneuchi' },
          { position: 'DeCurret', name: 'Yusuke Tanomogi' },
          { position: 'Flatt Security', name: 'stypr' },
          { position: 'Flatt Security', name: 'Azara/Norihide Saito' },
          { position: 'CyberAgent, Inc.', name: 'Daisuke Takahashi' },
          { position: 'Mitsui Bussan Secure Directions, Inc.', name: 'Yuji Tounai' },
          { name: 'yy0931' },
        ],
      },
    ],
  },
  {
    order: 200,
    sectionName: 'SPECIAL THANKS',
    additionalClass: '',
    memberGroups: [
      {
        additionalClass: 'col-md-4 my-4',
        members: [
          { name: 'Crowi Team' },
          { position: 'Ambassador', name: 'Tsuyoshi Suzuki' },
          { name: 'JPCERT/CC' },
        ],
      },
      {
        additionalClass: 'col-12 staff-credit-mt-10rem',
        members: [
          { name: 'AND YOU' },
        ],
      },
    ],
  },
];

module.exports = contributors;
