declare const _exports: {
    default: string;
    'growi:crowi': string;
    'growi:crowi:express-init': string;
    'growi:models:external-account': string;
    'growi:routes:login': string;
    'growi:routes:login-passport': string;
    'growi:middleware:safe-redirect': string;
    'growi:service:PassportService': string;
    'growi:service:s2s-messaging:*': string;
    'growi:service:yjs': string;
    'growi:service:yjs:*': string;
    'growi:lib:search': string;
    'growi-plugin:*': string;
    'growi:service:search-delegator:elasticsearch': string;
    'growi:service:g2g-transfer': string;
    'growi:service:questionnaire': string;
    'growi:migration:add-installed-date-to-config': string;
    'growi:cli:bootstrap': string;
    'growi:cli:app': string;
    'growi:services:*': string;
    'growi:searchResultList': string;
    'growi:service:openai': string;
};
export = _exports;
