const contributors = [
  {
    sectionName: 'GROWI VILLAGE',
    sectionAdditionalClass: 'staff-credit-mt-10',
    memberAdditionalClass: 'col-md-12 my-4',
    members: [
      { position: 'Founder', name: 'yuki-takei' },
      { position: 'Soncho 1st', name: 'mizozobu' },
      { position: 'Soncho 2nd', name: 'yusuketk' },
    ],
  },
  {
    hideSectionName: true,
    sectionName: 'GROWI VILLAGE 2',
    sectionAdditionalClass: 'staff-credit-mb-10',
    memberAdditionalClass: 'col-md-6 my-4',
    members: [
      { name: 'utsushiiro' },
      { name: 'mayumorita' },
      { name: 'TatsuyaIse' },
      { name: 'shinoka7' },
      { name: 'SeiyaTashiro' },
      { name: 'itizawa' },
      { name: 'TsuyoshiSuzukief' },
      { name: 'Yuchan4342' },
      { name: 'ryu-sato' },
      { name: 'haruhikonyan' },
      { name: 'KazuyaNagase' },
      { name: 'kaishuu0123' },
      { name: 'kouki-o' },
      { name: 'Angola' },
    ],
  },
  {
    sectionName: 'CONTRIBUTER',
    sectionAdditionalClass: 'staff-credit-mt-10 staff-credit-mb-10',
    memberAdditionalClass: 'col-md-4',
    members: [
      { name: 'shield-9' },
      { name: 'yaodingyd' },
      { name: 'hitochan777' },
      { name: 'ttaka66' },
      { name: 'watagashi' },
      { name: 'nt-7' },
      { name: 'hideo54' },
      { name: 'wadahiro' },
      { name: 'shaminmeerankutty' },
      { name: 'fumitti' },
      { name: 'fmy' },
      { name: 'yaamai' },
      { name: 'ta2yak' },
      { name: 'ryo33' },
      { name: 'rabitarochan' },
      { name: 'r-tateshina' },
      { name: 'nekoruri' },
      { name: 'kmyk' },
      { name: 'aximov' },
    ],
  },
  {
    sectionName: 'SPECIAL THANKS',
    sectionAdditionalClass: 'staff-credit-mt-10 staff-credit-mb-10',
    memberAdditionalClass: 'col-md-4',
    members: [
      { name: 'Crowi Team' },
      { position: 'Ambassador', name: 'Tsuyoshi Suzuki' },
    ],
  },
];

module.exports = contributors;
